// Akademik yayınlar — Akademi sayfasındaki PublicationList tarafından kullanılır.
// Kaynak: İsparta Uygulamalı Bilimler Üniversitesi personel sayfası (YÖK Akademik).
// https://www.isparta.edu.tr/personel/01667/doc-dr-ahmet-ali-suzen
// Not: DOI/link bilgileri kaynakta toplu listelenmediğinden boş bırakıldı; doiUrl
// eklendikçe ilgili kayıtta "DOI / İncele" butonu otomatik aktifleşir.

export type PublicationType = 'makale' | 'kitap' | 'bildiri';

export interface Publication {
  id: string;
  baslik: string;
  yazarlar: string;
  dergiVeyaKonferans: string;
  yil: number;
  tur: PublicationType;
  doiUrl?: string;
}

const rawPublications: Publication[] = [
  // ——— Makaleler ———
  {
    id: 'm-1',
    baslik:
      'Anthropometric measurements of human faces generated by artificial intelligence',
    yazarlar: 'YILDIZ Z., SÜZEN A. A., CEYLAN O.',
    dergiVeyaKonferans: 'Anatomy',
    yil: 2025,
    tur: 'makale',
  },
  {
    id: 'm-2',
    baslik:
      'Cyber Security in the Financial Sector in Turkey: Threats, Actors and Defense Strategies',
    yazarlar: 'SÜZEN A. A., Erdem M.',
    dergiVeyaKonferans: 'Yalvaç Akademi Dergisi',
    yil: 2025,
    tur: 'makale',
  },
  {
    id: 'm-3',
    baslik:
      'Robustness Assessment of Data Loss Prevention (DLP) Software for Data Leakage against Different Data Types and Sources',
    yazarlar: 'SÜZEN A. A., CEYLAN O.',
    dergiVeyaKonferans:
      'International Journal of Education and Management Engineering',
    yil: 2025,
    tur: 'makale',
  },
  {
    id: 'm-4',
    baslik:
      'Advantages and Disadvantages of Retrieval Augmented Generation (RAG) in Generative AI',
    yazarlar: 'Toy M. T., SÜZEN A. A.',
    dergiVeyaKonferans:
      'International Journal of 3D Printing Technologies and Digital Industry',
    yil: 2025,
    tur: 'makale',
  },
  {
    id: 'm-5',
    baslik: 'IoT Security and Software Testing',
    yazarlar: 'SÜZEN A. A., DUMAN B., ÇETLENBİK O. C.',
    dergiVeyaKonferans: 'Yalvaç Akademi Dergisi',
    yil: 2024,
    tur: 'makale',
  },
  {
    id: 'm-6',
    baslik:
      'Determining the Landing Error Scoring System after a Jump by Artificial Intelligence',
    yazarlar: 'ERCAN S., SÜZEN A. A., BAŞKURT F., BAŞKURT Z.',
    dergiVeyaKonferans: 'Online Türk Sağlık Bilimleri Dergisi',
    yil: 2024,
    tur: 'makale',
  },
  {
    id: 'm-7',
    baslik:
      'The Advantages and Implementation Challenges within the Scope of the Basic Principles of Transition to Zero Trust Architecture',
    yazarlar: 'SÜZEN A. A., CEYLAN O.',
    dergiVeyaKonferans:
      'International Journal of 3D Printing Technologies and Digital Industry',
    yil: 2024,
    tur: 'makale',
  },
  {
    id: 'm-8',
    baslik:
      'Examining the Social Engineering Attack Vector in the Line of Data Breach',
    yazarlar: 'SÜZEN A. A.',
    dergiVeyaKonferans: 'Teknik Bilimler Dergisi',
    yil: 2023,
    tur: 'makale',
  },
  {
    id: 'm-9',
    baslik:
      'Otonom mobil robotların güvenli veri iletimi için hibrit şifreleme yaklaşımı',
    yazarlar: 'Erbil M. E., SÜZEN A. A., BAYRAKÇI H. C.',
    dergiVeyaKonferans: 'Uluslararası Teknolojik Bilimler Dergisi',
    yil: 2023,
    tur: 'makale',
  },
  {
    id: 'm-10',
    baslik:
      'Location-Based AI-Assisted Filation Software for Isolation of Epidemic Diseases',
    yazarlar: 'SÜZEN A. A., DUMAN B.',
    dergiVeyaKonferans:
      'International Journal of Engineering and Innovative Research',
    yil: 2023,
    tur: 'makale',
  },
  {
    id: 'm-11',
    baslik:
      "Modeling of IoT-Based Additive Manufacturing Machine's Digital Twin for Error Detection",
    yazarlar: 'DUMAN B., SÜZEN A. A.',
    dergiVeyaKonferans: 'Mühendislik Bilimleri ve Tasarım Dergisi',
    yil: 2023,
    tur: 'makale',
  },
  {
    id: 'm-12',
    baslik:
      'Cyber Attacks for Data Breach and Possible Defense Strategies in Internet of Healthcare Things Ecosystem',
    yazarlar: 'SÜZEN A. A.',
    dergiVeyaKonferans:
      'International Journal of 3D Printing Technologies and Digital Industry',
    yil: 2023,
    tur: 'makale',
  },
  {
    id: 'm-13',
    baslik:
      'Classification of Reinforcement Costs of Masonry Walls Using Hybrid Extreme Gradient Boosting and Softmax',
    yazarlar: 'ALKAN Ç. M., SÜZEN A. A.',
    dergiVeyaKonferans: 'Journal of Engineering Research (SCI)',
    yil: 2023,
    tur: 'makale',
  },
  {
    id: 'm-14',
    baslik:
      'Analysing and Carving MS Word and PDF Files from RAM Images on Windows',
    yazarlar: 'TAŞDELEN K., SÜZEN A. A.',
    dergiVeyaKonferans: 'Tehnicki Vjesnik - Technical Gazette (SCI)',
    yil: 2022,
    tur: 'makale',
  },
  {
    id: 'm-15',
    baslik:
      'An Investigation into Artificial Intelligence and the Challenges it Faces',
    yazarlar: 'Saini N., Hakami W. A., Dixit N., Chaudhary A., SÜZEN A. A.',
    dergiVeyaKonferans: 'NeuroQuantology',
    yil: 2022,
    tur: 'makale',
  },
  {
    id: 'm-16',
    baslik: 'A Study on Deep Learning Based Classification of Flower Images',
    yazarlar: 'DUMAN B., SÜZEN A. A.',
    dergiVeyaKonferans:
      'International Journal of Advanced Networking and Applications (IJANA)',
    yil: 2022,
    tur: 'makale',
  },
  {
    id: 'm-17',
    baslik:
      'Blockchain-Based Secure Credit Card Storage System for E-Commerce',
    yazarlar: 'SÜZEN A. A., DUMAN B.',
    dergiVeyaKonferans:
      'Sakarya University Journal of Computer and Information Sciences',
    yil: 2021,
    tur: 'makale',
  },
  {
    id: 'm-18',
    baslik:
      'Prediction of Rebound Amount in Dry Mix Shotcrete by a Fast Adaboosting Neural Network',
    yazarlar: 'ALKAN M., İNCE H. H., ALKAN Ç. M., SÜZEN A. A.',
    dergiVeyaKonferans: 'Technical Gazette (SCI)',
    yil: 2021,
    tur: 'makale',
  },
  {
    id: 'm-19',
    baslik:
      'Developing a Multi-Level Intrusion Detection System Using Hybrid-DBN',
    yazarlar: 'SÜZEN A. A.',
    dergiVeyaKonferans:
      'Journal of Ambient Intelligence and Humanized Computing (SCI)',
    yil: 2021,
    tur: 'makale',
  },
  {
    id: 'm-20',
    baslik:
      'UNI-CAPTCHA: A Novel Robust and Dynamic User-Non-Interaction CAPTCHA Model Based on Hybrid biLSTM+Softmax',
    yazarlar: 'SÜZEN A. A.',
    dergiVeyaKonferans:
      'Journal of Information Security and Applications (SCI)',
    yil: 2021,
    tur: 'makale',
  },
  {
    id: 'm-21',
    baslik:
      'Experimental and DBN-Based Neural Network Extraction of Radiation Attenuation Coefficient of Dry Mixture Shotcrete',
    yazarlar: 'ALKAN Ç. M., KAPLAN A. N., SÜZEN A. A.',
    dergiVeyaKonferans: 'Radiation Physics and Chemistry (SCI)',
    yil: 2021,
    tur: 'makale',
  },
  {
    id: 'm-22',
    baslik:
      'Experimental Examination of the Behavior of Shotcrete-Reinforced Masonry Walls and XGBoost Neural Network Prediction Model',
    yazarlar: 'ALKAN Ç. M., İNCE G., TEKELİ H., SÜZEN A. A.',
    dergiVeyaKonferans: 'Arabian Journal for Science and Engineering (SCI)',
    yil: 2021,
    tur: 'makale',
  },
  {
    id: 'm-23',
    baslik:
      'Assessment and Application of Deep Learning Algorithms in Civil Engineering',
    yazarlar: 'ALKAN Ç. M., SÜZEN A. A.',
    dergiVeyaKonferans: 'El-Cezeri Journal of Science and Engineering',
    yil: 2020,
    tur: 'makale',
  },
  {
    id: 'm-24',
    baslik:
      'Real-Time Tree Counting Android Application and Central Monitoring System',
    yazarlar: 'SÜZEN A. A., GÜRFİDAN R., KAYAALP K., ŞİMŞEK M. A.',
    dergiVeyaKonferans:
      'International Journal of Information Technology and Computer Science',
    yil: 2020,
    tur: 'makale',
  },
  {
    id: 'm-25',
    baslik:
      'A Novel Approach to Machine Learning Application to Protection Privacy Data in Healthcare: Federated Learning',
    yazarlar: 'SÜZEN A. A., ŞİMŞEK M. A.',
    dergiVeyaKonferans: 'Namık Kemal Tıp Dergisi',
    yil: 2020,
    tur: 'makale',
  },
  {
    id: 'm-26',
    baslik:
      'A Risk-Assessment of Cyber Attacks and Defense Strategies in Industry 4.0 Ecosystem',
    yazarlar: 'SÜZEN A. A.',
    dergiVeyaKonferans:
      'International Journal of Computer Network and Information Security (IJCNIS)',
    yil: 2020,
    tur: 'makale',
  },
  {
    id: 'm-27',
    baslik:
      'Depresyon Teşhisi Süresinin Kısaltılması için Kısmi Ölçek Sorularının Cevaplarının Derin Sinir Ağları ile Tahmin Edilmesi',
    yazarlar: 'GÜRFİDAN R., SÜZEN A. A.',
    dergiVeyaKonferans: 'İzmir Tepecik Eğitim Hastanesi Dergisi',
    yil: 2020,
    tur: 'makale',
  },
  {
    id: 'm-28',
    baslik:
      'Fizik Tedavi ve Ortopedi Hastaları İçin Derin İnanç Ağı Temelli Yeni Bir Teşhis Koyma Yaklaşımı',
    yazarlar: 'YILDIZ Z., SÜZEN A. A.',
    dergiVeyaKonferans: 'İzmir Tepecik Eğitim Hastanesi Dergisi',
    yil: 2020,
    tur: 'makale',
  },
  {
    id: 'm-29',
    baslik:
      'Püskürtme Betonun Yaklaşık Maliyet Analizi İçin Uygulama Geliştirilmesi',
    yazarlar: 'ALKAN Ç. M., SÜZEN A. A., Şentürk İ.',
    dergiVeyaKonferans: 'Mühendislik Bilimleri ve Tasarım Dergisi',
    yil: 2020,
    tur: 'makale',
  },
  {
    id: 'm-30',
    baslik:
      'İnsan Yürüyüşünün Yapay Zekâyla Sınıflandırılması: Sistematik Bir Gözden Geçirme',
    yazarlar: 'BAŞKURT F., YILDIZ Z., SÜZEN A. A.',
    dergiVeyaKonferans:
      'Süleyman Demirel Üniversitesi Sağlık Bilimleri Dergisi',
    yil: 2020,
    tur: 'makale',
  },
  {
    id: 'm-31',
    baslik:
      'LSTM Derin Sinir Ağları İle Üniversite Giriş Sınavındaki Matematik Soru Sayılarının Konulara Göre Tahmini',
    yazarlar: 'SÜZEN A. A.',
    dergiVeyaKonferans: 'Engineering Sciences',
    yil: 2019,
    tur: 'makale',
  },
  {
    id: 'm-32',
    baslik:
      'The Attack Methodology to Wireless Domains of Things in Industry 4.0',
    yazarlar: 'SÜZEN A. A., ŞİMŞEK M. A., KAYAALP K., GÜRFİDAN R.',
    dergiVeyaKonferans: 'Nevşehir Bilim ve Teknoloji Dergisi',
    yil: 2019,
    tur: 'makale',
  },
  {
    id: 'm-33',
    baslik: 'Büyük Verilerde Gizlilik Tabanlı Yaklaşım: Federe Öğrenme',
    yazarlar: 'SÜZEN A. A., KAYAALP K.',
    dergiVeyaKonferans:
      'International Journal of 3D Printing Technologies and Digital Industry',
    yil: 2019,
    tur: 'makale',
  },
  {
    id: 'm-34',
    baslik: 'Prediction of Rebound in Shotcrete Using Deep Bi-Directional LSTM',
    yazarlar: 'SÜZEN A. A., ALKAN Ç. M.',
    dergiVeyaKonferans: 'Computers and Concrete (SCI)',
    yil: 2019,
    tur: 'makale',
  },
  {
    id: 'm-35',
    baslik: 'Development of Kernel Mode RAM Driver for RAM Image on Windows',
    yazarlar: 'SÜZEN A. A., TAŞDELEN K., KÜÇÜKSİLLE E. U.',
    dergiVeyaKonferans:
      'Süleyman Demirel Üniversitesi Fen Bilimleri Enstitüsü Dergisi',
    yil: 2019,
    tur: 'makale',
  },
  {
    id: 'm-36',
    baslik: 'Arduino ile Bilgisayar Kontrollü Serbest Düşme Deney Sistemi',
    yazarlar: 'SÜZEN A. A., KAYAALP K.',
    dergiVeyaKonferans: 'Mühendislik Bilimleri ve Tasarım Dergisi',
    yil: 2019,
    tur: 'makale',
  },
  {
    id: 'm-37',
    baslik: 'Skolyoz Hastalığının Tespiti için Taşınabilir Cihaz Tasarımı',
    yazarlar: 'SÜZEN A. A., YILDIZ Z., KAYAALP K., CEYLAN O., ARABACI E.',
    dergiVeyaKonferans: 'European Journal of Science and Technology',
    yil: 2019,
    tur: 'makale',
  },
  {
    id: 'm-38',
    baslik:
      'LSTM tabanlı Derin Sinir Ağı ile Ayak Taban Basınç Verilerinden VKİ Durumlarının Sınıflandırılması',
    yazarlar: 'SÜZEN A. A., YILDIZ Z., YILMAZ M. T.',
    dergiVeyaKonferans: 'Bitlis Eren Üniversitesi Fen Bilimleri Dergisi',
    yil: 2019,
    tur: 'makale',
  },
  {
    id: 'm-39',
    baslik: 'Havalimanları İçin Bagaj Teslimat Sistemi',
    yazarlar: 'SÜZEN A. A., TAŞDELEN K.',
    dergiVeyaKonferans: 'SDÜ Uluslararası Teknolojik Bilimler Dergisi',
    yil: 2018,
    tur: 'makale',
  },
  {
    id: 'm-40',
    baslik:
      'Web Based Tracking of Vehicle Fault and Performance Data on OBD II',
    yazarlar: 'SÜZEN A. A., KAYAALP K.',
    dergiVeyaKonferans: 'Scientific Journal of Mehmet Akif Ersoy University',
    yil: 2018,
    tur: 'makale',
  },
  {
    id: 'm-41',
    baslik: 'Elektrik Sayaçlarının Uzaktan Okunması ve Enerji Analizi',
    yazarlar: 'GÜÇLÜ B., BAYRAKÇI H. C., SÜZEN A. A.',
    dergiVeyaKonferans: 'SDÜ Uluslararası Teknolojik Bilimler Dergisi',
    yil: 2018,
    tur: 'makale',
  },
  {
    id: 'm-42',
    baslik: 'Personal Custom Hallux Valgus Splint Design for 3D Printer',
    yazarlar: 'SÜZEN A. A., YILDIZ Z., KAYAALP K., CEYLAN O.',
    dergiVeyaKonferans:
      'International Journal of 3D Printing Technologies and Digital Industry',
    yil: 2018,
    tur: 'makale',
  },
  {
    id: 'm-43',
    baslik: 'Recovering Multimedia Files from a Memory Image',
    yazarlar: 'SÜZEN A. A., TAŞDELEN K.',
    dergiVeyaKonferans: 'Journal of Polytechnic',
    yil: 2018,
    tur: 'makale',
  },
  {
    id: 'm-44',
    baslik:
      'Internet Controlled Smart Tea Machine Design with Arduino and Tea Consumption Analysis',
    yazarlar: 'KAYAALP K., CEYLAN O., SÜZEN A. A., YILDIZ Z.',
    dergiVeyaKonferans: 'Uluborlu Mesleki Bilimler Dergisi',
    yil: 2018,
    tur: 'makale',
  },
  {
    id: 'm-45',
    baslik: 'Kafa Hareketleri İle Kontrol Edilebilen Tekerlekli Sandalye',
    yazarlar: 'SÜZEN A. A., DENİZ Ö., ÇETİN A.',
    dergiVeyaKonferans:
      'Mehmet Akif Ersoy Üniversitesi Fen Bilimleri Enstitüsü Dergisi',
    yil: 2017,
    tur: 'makale',
  },
  {
    id: 'm-46',
    baslik: 'Arduino Kontrollü Çizim Robotu',
    yazarlar: 'SÜZEN A. A., CEYLAN O., ÇETİN A., ULUSOY A.',
    dergiVeyaKonferans:
      'Mehmet Akif Ersoy Üniversitesi Fen Bilimleri Enstitüsü Dergisi',
    yil: 2017,
    tur: 'makale',
  },
  {
    id: 'm-47',
    baslik: 'Anlamsal Web Teknolojisi İle İçerik Arama',
    yazarlar: 'SÜZEN A. A., TAŞDELEN K.',
    dergiVeyaKonferans: 'El-Cezeri Journal of Science and Engineering',
    yil: 2016,
    tur: 'makale',
  },
  {
    id: 'm-48',
    baslik: 'Kinect Teknolojisi Kullanılarak Engelliler İçin Ev Otomasyonu',
    yazarlar: 'SÜZEN A. A., TAŞDELEN K.',
    dergiVeyaKonferans: 'SDÜ Uluslararası Teknolojik Bilimler Dergisi',
    yil: 2013,
    tur: 'makale',
  },

  // ——— Bildiriler ———
  {
    id: 'b-1',
    baslik: 'Cyberattacks on Autonomous Vehicles',
    yazarlar: 'TUNCER İ., SÜZEN A. A.',
    dergiVeyaKonferans:
      '3rd International Conference on Recent and Innovative Results in Engineering and Technology (ICRIRET 2025), Konya',
    yil: 2025,
    tur: 'bildiri',
  },
  {
    id: 'b-2',
    baslik:
      'Using Explainable Artificial Intelligence in Buy and Sell Signals in the Cryptocurrency Market',
    yazarlar: 'SÜZEN A. A., ÇETLENBİK O. C.',
    dergiVeyaKonferans:
      '4th International Conference on Contemporary Academic Research (ICCAR 2025), Konya',
    yil: 2025,
    tur: 'bildiri',
  },
  {
    id: 'b-3',
    baslik:
      'DistilBERT Algoritmasının Phishing Saldırılarının Sınıflandırılmasında Kullanılması',
    yazarlar: 'CENGİZ E., SÜZEN A. A.',
    dergiVeyaKonferans:
      '3rd International Conference on Recent Academic Studies',
    yil: 2024,
    tur: 'bildiri',
  },
  {
    id: 'b-4',
    baslik: 'Quantum Computing and Its Evaluation in Cyber Security',
    yazarlar: 'SÜZEN A. A., ÇİFTÇİ Y.',
    dergiVeyaKonferans:
      '3rd International Conference on Contemporary Academic Research',
    yil: 2024,
    tur: 'bildiri',
  },
  {
    id: 'b-5',
    baslik:
      'Hybrid Approaches to Price Prediction in Cryptocurrency Markets: Machine Learning and Technical Analysis',
    yazarlar: 'SÜZEN A. A., ÇETLENBİK O. C.',
    dergiVeyaKonferans:
      '5th International Conference on Engineering and Applied Natural Sciences (ICEANS 2024)',
    yil: 2024,
    tur: 'bildiri',
  },
  {
    id: 'b-6',
    baslik: 'Classification of Phishing Attacks Using the RoBERTa Model',
    yazarlar: 'GÜRFİDAN R., ÇETLENBİK O. C., SÜZEN A. A.',
    dergiVeyaKonferans:
      '4th International Conference on Innovative Academic Studies (ICIAS 2024), Konya',
    yil: 2024,
    tur: 'bildiri',
  },
  {
    id: 'b-7',
    baslik:
      'The Role of Explainable Artificial Intelligence in Diagnosing and Mitigating Potential Data Breach Risks in Healthcare',
    yazarlar: 'SÜZEN A. A., YILDIZ Z.',
    dergiVeyaKonferans:
      '2nd International Conference on Contemporary Academic Research',
    yil: 2023,
    tur: 'bildiri',
  },
  {
    id: 'b-8',
    baslik: 'Metaverse in Medicine',
    yazarlar: 'SÜZEN A. A., YILDIZ Z.',
    dergiVeyaKonferans:
      '2nd International Conference on Contemporary Academic Research',
    yil: 2023,
    tur: 'bildiri',
  },
  {
    id: 'b-9',
    baslik:
      'Web Uygulama Zafiyetlerinin Keşfinde Açıklanabilir Yapay Zekânın Yeri',
    yazarlar: 'SÜZEN A. A., BAŞ E.',
    dergiVeyaKonferans:
      'International Conference on Applied Engineering and Natural Sciences',
    yil: 2023,
    tur: 'bildiri',
  },
  {
    id: 'b-10',
    baslik:
      'Kurumsal Ağlara Yapılan Saldırılarda Açıklanabilir Yapay Zekânın Yeri',
    yazarlar: 'SÜZEN A. A., YAZ Ö.',
    dergiVeyaKonferans:
      '5th International Conference on Applied Engineering and Natural Sciences',
    yil: 2023,
    tur: 'bildiri',
  },
  {
    id: 'b-11',
    baslik:
      'The Resilience of Unmanned Aerial Vehicles to Cyberattacks and Assessment of Potential Threats',
    yazarlar: 'SÜZEN A. A.',
    dergiVeyaKonferans:
      '4th International Conference on Artificial Intelligence and Applied Mathematics in Engineering',
    yil: 2023,
    tur: 'bildiri',
  },
  {
    id: 'b-12',
    baslik:
      'Examining the Results of Phishing Attacks in a Sample Attack Simulation',
    yazarlar: 'SÜZEN A. A., ÇETLENBİK O. C.',
    dergiVeyaKonferans:
      '1st International Conference on Innovative Academic Studies',
    yil: 2022,
    tur: 'bildiri',
  },
  {
    id: 'b-13',
    baslik: 'Vulnerability Assessment of Server with Shodan Query',
    yazarlar: 'SÜZEN A. A., GÜRFİDAN R.',
    dergiVeyaKonferans:
      'International Congress on Innovation Technologies & Engineering',
    yil: 2022,
    tur: 'bildiri',
  },
  {
    id: 'b-14',
    baslik:
      'ERC-20 Token Creating and Implementation of Security Measures in Solidity: AASCOIN',
    yazarlar: 'SÜZEN A. A., CEYLAN O.',
    dergiVeyaKonferans:
      'International Blockchain and Cryptocurrency Conference, Ankara',
    yil: 2021,
    tur: 'bildiri',
  },
  {
    id: 'b-15',
    baslik:
      'Prediction of Electricity Consumption Values for Commercial and Residential Buildings Using Bi-Directional LSTM',
    yazarlar: 'SÜZEN A. A., DUMAN B.',
    dergiVeyaKonferans:
      'IV. International Congress on New Trends in Science, Engineering and Technology',
    yil: 2020,
    tur: 'bildiri',
  },
  {
    id: 'b-16',
    baslik:
      'Benchmark Analysis of Jetson TX2, Jetson Nano and Raspberry Pi using Deep-CNN',
    yazarlar: 'SÜZEN A. A., DUMAN B., Şen E. B.',
    dergiVeyaKonferans:
      '2020 International Congress on Human-Computer Interaction, Optimization and Robotic Applications (HORA), Ankara',
    yil: 2020,
    tur: 'bildiri',
  },
  {
    id: 'b-17',
    baslik: 'Vehicle Price Determination by Neural Fuzzy Inference Method',
    yazarlar: 'GÜRFİDAN R., SÜZEN A. A.',
    dergiVeyaKonferans:
      'International Conference on Artificial Intelligence towards Industry 4.0 (ICAII4.0)',
    yil: 2019,
    tur: 'bildiri',
  },
  {
    id: 'b-18',
    baslik:
      'Fashion Classification Using 2-Channel Deep Convolutional Neural Network',
    yazarlar: 'SÜZEN A. A., GÜRFİDAN R., KAYAALP K.',
    dergiVeyaKonferans:
      '2nd International Conference on Technology and Science, Burdur',
    yil: 2019,
    tur: 'bildiri',
  },
  {
    id: 'b-19',
    baslik: 'RFID Teknolojisi Kullanılarak Alışveriş Arabası Takip Sistemi',
    yazarlar: 'KAYAALP K., SÜZEN A. A., GÜRFİDAN R.',
    dergiVeyaKonferans:
      '2nd International Conference on Technology and Science, Burdur',
    yil: 2019,
    tur: 'bildiri',
  },
  {
    id: 'b-20',
    baslik: 'Sokak Hayvanları İçin Akıllı Yemek Konteynırı Tasarımı',
    yazarlar: 'GÜRFİDAN R., SÜZEN A. A., KAYAALP K.',
    dergiVeyaKonferans:
      '2nd International Conference on Technology and Science, Burdur',
    yil: 2019,
    tur: 'bildiri',
  },
  {
    id: 'b-21',
    baslik:
      'Classification of Induction Motors by Fault Type with Bidirectional Long-Short Term Memory Method',
    yazarlar: 'SÜZEN A. A., KAYAALP K.',
    dergiVeyaKonferans:
      '4th International Symposium on Innovative Approaches in Engineering and Natural Sciences, Samsun',
    yil: 2019,
    tur: 'bildiri',
  },
  {
    id: 'b-22',
    baslik:
      'Gezgin Satıcı Probleminin Genetik Algoritma ile Çözümü Üzerine Bir Uygulama',
    yazarlar: 'ŞİMŞEK M. A., SÜZEN A. A., GÜRFİDAN R., KAYAALP K.',
    dergiVeyaKonferans:
      '2nd International Congress on Engineering and Architecture, Muğla',
    yil: 2019,
    tur: 'bildiri',
  },
  {
    id: 'b-23',
    baslik:
      'Bulut Tabanlı Açık Araziler için Meyve Miktarı Sayma Android Uygulaması',
    yazarlar: 'GÜRFİDAN R., ŞİMŞEK M. A., KAYAALP K., SÜZEN A. A.',
    dergiVeyaKonferans:
      '2nd International Congress on Engineering and Architecture',
    yil: 2019,
    tur: 'bildiri',
  },
  {
    id: 'b-24',
    baslik: 'Mobil Geriatri Uyarı Sistemi: MOGES',
    yazarlar: 'SÜZEN A. A., KAYAALP K.',
    dergiVeyaKonferans: 'International Conference on Technology and Science',
    yil: 2018,
    tur: 'bildiri',
  },
  {
    id: 'b-25',
    baslik: 'Developing LPG Price Tracking Software for Android Systems',
    yazarlar: 'KAYAALP K., SÜZEN A. A., CEYLAN O.',
    dergiVeyaKonferans:
      'International Conference on Technology and Science, Antalya',
    yil: 2018,
    tur: 'bildiri',
  },
  {
    id: 'b-26',
    baslik: 'Cloud-Based Mobile Notification System',
    yazarlar: 'SÜZEN A. A., KAYAALP K., ŞİMŞEK M. A., CEYLAN O.',
    dergiVeyaKonferans: 'International Conference on Technology and Science',
    yil: 2018,
    tur: 'bildiri',
  },
  {
    id: 'b-27',
    baslik: 'Kinect ile İnteraktif Emlak Vitrini',
    yazarlar: 'KAYAALP K., SÜZEN A. A.',
    dergiVeyaKonferans: 'International Conference on Technology and Science',
    yil: 2018,
    tur: 'bildiri',
  },
  {
    id: 'b-28',
    baslik: 'Server Based Laboratory Design with Raspberry Pi',
    yazarlar: 'KAYAALP K., SÜZEN A. A.',
    dergiVeyaKonferans: 'International Academic Research Congress',
    yil: 2018,
    tur: 'bildiri',
  },
  {
    id: 'b-29',
    baslik:
      'Forecasting Temperature with Deep Learning Methods: Samples of Isparta Province',
    yazarlar: 'SÜZEN A. A., KAYAALP K.',
    dergiVeyaKonferans: 'International Academic Research Congress',
    yil: 2018,
    tur: 'bildiri',
  },
  {
    id: 'b-30',
    baslik: 'Design of Efficiency Controlled Cleaning System for Solar Panel',
    yazarlar: 'ÖZDEMİR A., ALADAĞ B., TAŞDELEN K., SÜZEN A. A.',
    dergiVeyaKonferans: 'International Conference on Science and Technology',
    yil: 2018,
    tur: 'bildiri',
  },
  {
    id: 'b-31',
    baslik:
      'Design of RFID Controlled Wireless Charging System for Electric Vehicles',
    yazarlar: 'TÜRKMENOĞLU H., MAMMEDOV N., TAŞDELEN K., SÜZEN A. A.',
    dergiVeyaKonferans: 'International Conference on Science and Technology',
    yil: 2018,
    tur: 'bildiri',
  },
  {
    id: 'b-32',
    baslik: 'Trafik Kazalarına Acil Müdahale Sistemi: Kurtaran Çağrı',
    yazarlar: 'TAŞDELEN K., SÜZEN A. A., EREN S., ENSAR E.',
    dergiVeyaKonferans: 'European Conference on Science, Art & Culture',
    yil: 2018,
    tur: 'bildiri',
  },
  {
    id: 'b-33',
    baslik: 'Audio Controlled Home Automation Design',
    yazarlar: 'TAŞDELEN K., SÜZEN A. A., İNCE M., YILMAZ A.',
    dergiVeyaKonferans: 'European Conference on Science, Art & Culture',
    yil: 2018,
    tur: 'bildiri',
  },
  {
    id: 'b-34',
    baslik:
      'The Effects of DGS on the Review of Mathematics in Vocational Schools: The Case of Uluborlu Selahattin Karasoy Vocational School',
    yazarlar: 'SÜZEN A. A., CEYLAN O., DOĞRUKOL S.',
    dergiVeyaKonferans: 'Uluslararası Mesleki Bilimler Sempozyumu',
    yil: 2017,
    tur: 'bildiri',
  },
  {
    id: 'b-35',
    baslik:
      'The Development of WPF-Based Slicing Tool for 3D Printers: Digital Painter',
    yazarlar: 'SÜZEN A. A., ARABACI E., CEYLAN O.',
    dergiVeyaKonferans: 'Uluslararası Mesleki Bilimler Sempozyumu',
    yil: 2017,
    tur: 'bildiri',
  },
  {
    id: 'b-36',
    baslik: 'Rapid Transit System for Students with Arduino',
    yazarlar: 'SÜZEN A. A., ARABACI E., CEYLAN O.',
    dergiVeyaKonferans: 'Uluslararası Mesleki Bilimler Sempozyumu',
    yil: 2017,
    tur: 'bildiri',
  },
  {
    id: 'b-37',
    baslik: 'Programmable Intelligent Irrigation Manager Design',
    yazarlar: 'ARABACI E., SÜZEN A. A.',
    dergiVeyaKonferans:
      'VI. International Vocational Schools Symposium, Bosna',
    yil: 2017,
    tur: 'bildiri',
  },
  {
    id: 'b-38',
    baslik: 'Access to User Accounts Through RAM Image for Computer Forensics',
    yazarlar: 'SÜZEN A. A., TAŞDELEN K., KÜÇÜKSİLLE E. U.',
    dergiVeyaKonferans:
      'International Conference on Research in Education and Science',
    yil: 2016,
    tur: 'bildiri',
  },
  {
    id: 'b-39',
    baslik: 'Volatile Data Analysis and Methods in Computer Forensics',
    yazarlar: 'SÜZEN A. A., TAŞDELEN K., KÜÇÜKSİLLE E. U.',
    dergiVeyaKonferans:
      'International Conference on Research in Education and Science',
    yil: 2016,
    tur: 'bildiri',
  },
  {
    id: 'b-40',
    baslik: 'Microsoft Kinect ile Örnek Bir Uygulama: Piyano',
    yazarlar: 'SÜZEN A. A., TAŞDELEN K.',
    dergiVeyaKonferans: 'Akademik Bilişim 2013',
    yil: 2013,
    tur: 'bildiri',
  },

  // ——— Kitaplar ve Kitap Bölümleri ———
  {
    id: 'k-1',
    baslik:
      'Disiplinlerarası Mühendislik ve Teknik Bilimler Çalışmaları (Kitap Bölümü, ss. 25-53)',
    yazarlar: 'SÜZEN A. A., ÖNCEL M.',
    dergiVeyaKonferans: 'IKSAD Yayınevi',
    yil: 2025,
    tur: 'kitap',
  },
  {
    id: 'k-2',
    baslik:
      'Doğa ve Mühendislik Bilimlerinde Güncel Tartışmalar 8 (Kitap Bölümü, ss. 771-781)',
    yazarlar: 'İşçi A., YÜNLÜ L., SÜZEN A. A.',
    dergiVeyaKonferans: 'Bilgin Kültür Sanat Yayınları',
    yil: 2023,
    tur: 'kitap',
  },
  {
    id: 'k-3',
    baslik:
      'Kişisel Verilerin Korunması Kapsamında Güncel Siber Saldırılar ve Son Kullanıcı Güvenliği',
    yazarlar: 'SÜZEN A. A., GÜRFİDAN R.',
    dergiVeyaKonferans: 'IKSAD Publishing House',
    yil: 2022,
    tur: 'kitap',
  },
  {
    id: 'k-4',
    baslik: 'Internet of Medical Things (Kitap Bölümü, ss. 35-54)',
    yazarlar: 'SÜZEN A. A., DUMAN B.',
    dergiVeyaKonferans: 'Springer',
    yil: 2021,
    tur: 'kitap',
  },
  {
    id: 'k-5',
    baslik: 'Bilim ve Teknoloji Araştırmaları 2019 (Kitap Bölümü, ss. 23-31)',
    yazarlar: 'SÜZEN A. A., KAYAALP K.',
    dergiVeyaKonferans: 'Çizgi Yayınevi',
    yil: 2019,
    tur: 'kitap',
  },
  {
    id: 'k-6',
    baslik: 'Bilim ve Teknoloji Araştırmaları 2019 (Kitap Bölümü, ss. 15-22)',
    yazarlar: 'YILDIZ Z., SÜZEN A. A.',
    dergiVeyaKonferans: 'Çizgi Yayınevi',
    yil: 2019,
    tur: 'kitap',
  },
  {
    id: 'k-7',
    baslik: 'C Sharp Çözümlü Soru Bankası',
    yazarlar: 'SÜZEN A. A., KAYAALP K., ŞİMŞEK M. A.',
    dergiVeyaKonferans: 'Kodlab Yayınevi',
    yil: 2019,
    tur: 'kitap',
  },
  {
    id: 'k-8',
    baslik: 'Derin Öğrenme ve Türkiyedeki Uygulamaları',
    yazarlar: 'KAYAALP K., SÜZEN A. A.',
    dergiVeyaKonferans: 'IKSAD International Publishing House',
    yil: 2018,
    tur: 'kitap',
  },
  {
    id: 'k-9',
    baslik: 'Robot Programlama',
    yazarlar: 'SÜZEN A. A., ULUKUŞ S.',
    dergiVeyaKonferans: 'Kodlab',
    yil: 2011,
    tur: 'kitap',
  },
  {
    id: 'k-10',
    baslik: 'WPF',
    yazarlar: 'SÜZEN A. A.',
    dergiVeyaKonferans: 'Kodlab',
    yil: 2011,
    tur: 'kitap',
  },
  {
    id: 'k-11',
    baslik: 'Silverlight 4',
    yazarlar: 'SÜZEN A. A.',
    dergiVeyaKonferans: 'Kodlab',
    yil: 2011,
    tur: 'kitap',
  },
];

// Kaynak sayfada (isparta.edu.tr / YÖK Akademik) gerçekten DOI bağlantısı bulunan
// yayınlar. Yalnızca buradaki kayıtlarda "İncele" butonu DOI'ye yönlendirir.
const doiById: Record<string, string> = {
  'm-1': 'https://doi.org/10.2399/ana.25.1619768',
  'm-2': 'https://doi.org/10.57120/yalvac.1758073',
  'm-3': 'https://doi.org/10.5815/ijeme.2025.02.01',
  'm-4': 'https://doi.org/10.46519/ij3dptdi.1757444',
  'm-5': 'https://doi.org/10.57120/yalvac.1437571',
  'm-6': 'https://doi.org/10.26453/otjhs.1296565',
  'm-7': 'https://doi.org/10.46519/ij3dptdi.1556319',
  'm-8': 'https://doi.org/10.35354/tbed.1310185',
  'm-9': 'https://doi.org/10.55974/utbd.1311229',
  'm-10': 'https://doi.org/10.47933/ijeir.1334065',
  'm-11': 'https://doi.org/10.21923/jesd.1251972',
  'm-12': 'https://doi.org/10.46519/ij3dptdi.1240743',
  'm-13': 'https://doi.org/10.36909/jer.13747',
  'm-14': 'https://doi.org/10.17559/TV-20210218122046',
  'm-15': 'https://doi.org/10.14704/nq.2022.20.1.NQ22333',
  'm-16': 'https://doi.org/10.35444/IJANA.2022.14209',
  'm-17': 'https://doi.org/10.35377/saucis.04.02.895764',
  'm-18': 'https://doi.org/10.17559/TV-20200422014902',
  'm-19': 'https://doi.org/10.1007/s12652-020-02271-w',
  'm-20': 'https://doi.org/10.1016/j.jisa.2021.103036',
  'm-21': 'https://doi.org/10.1016/j.radphyschem.2021.109636',
  'm-22': 'https://doi.org/10.1007/s13369-021-05466-1',
  'm-23': 'https://doi.org/10.31202/ecjse.679113',
  'm-24': 'https://doi.org/10.5815/ijitcs.2020.02.02',
  'm-25': 'https://doi.org/10.37696/nkmj.660762',
  'm-26': 'https://doi.org/10.5815/ijcnis.2020.01.01',
  'm-29': 'https://doi.org/10.21923/jesd.562008',
  'm-31': 'https://doi.org/10.12739/NWSA.2019.14.3.1A0436',
  'm-32': 'https://doi.org/10.17100/nevbiltek.557886',
  'm-34': 'https://doi.org/10.12989/cac.2019.24.6.555',
  'm-35': 'https://doi.org/10.19113/sdufenbed.529039',
  'm-36': 'https://doi.org/10.21923/jesd.547876',
  'm-37': 'https://doi.org/10.31590/ejosat.534572',
  'm-38': 'https://doi.org/10.17798/bitlisfen.540273',
  'm-43': 'https://doi.org/10.2339/politeknik.417767',
};

export const publications: Publication[] = rawPublications.map((publication) =>
  doiById[publication.id]
    ? { ...publication, doiUrl: doiById[publication.id] }
    : publication,
);
